### ISSUE TITLE
Raster layer browser

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/jupytergis#10]
When implementing #9, a raster layer browser should be created. We could use https://github.com/geopandas/xyzservices/blob/main/provider_sources/xyzservices-providers.json to automatically populate this browser **at build time**. Ideally, it would look like the felt browser (see screenshot) and the pre-populated raster layer options would show a thumbnail (also generated at build time).

Of course, we should still provide the option to define a custom raster layer from a user-defined URL.

![Screenshot from 2024-06-19 11-30-49](https://github.com/QuantStack/jupytergis/assets/21197331/9a28fdcb-24a4-46e4-8c69-1f9cf5bef7e1)

**Comment by brichet** [comment]
Closing as completed by https://github.com/QuantStack/jupytergis/pull/16
