### ISSUE TITLE
PMTiles support

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/jupytergis#36]
https://maplibre.org/maplibre-gl-js/docs/examples/pmtiles

See also how leafmap implements it using maplibre Python (very similar):
- examples https://leafmap.org/notebooks/82_pmtiles/
- implementation https://github.com/opengeos/leafmap/blob/e3e30d6f4ddd27d9ada0df737c8be3b14ce08504/leafmap/maplibregl.py#L1672

**Comment by martinRenou** [comment]
Note that this seems to [not be supported by QGIS](https://github.com/protomaps/PMTiles/issues/177) so our (future) qgis editor should probably not allow creating such layer

**Comment by gjmooney** [comment]
Added in #91
