### ISSUE TITLE
GeoJSON file path is not relative to the jGIS file

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/jupytergis#39]
Our logic to read the GeoJSON file path is not relative to the jGIS file, but to the server runtime path.

**Comment by davidbrochart** [comment]
I feel that having side files that are not referenced by a universal path (like a URL) is going to be a source of issues.
Maybe we could optionally bundle everything in a single archive, or something like SpatialLite?

**Comment by martinRenou** [comment]
I'm about to push a fix to the original issue in https://github.com/QuantStack/jupytergis/pull/38

> I feel that having side files that are not referenced by a universal path (like a URL) is going to be a source of issues.

Yeah, in the case of the Python API I think we don't have a choice but to embed the JSON data. The kernel may be running in whatever machine and we don't know what local file it may reference to unless it's explicitly uploaded to the JupyterLab drive.
I believe that when selected from the UI, it is fine and it is reliable to reference a JupyterLab drive file path.
