### ISSUE TITLE
Layer groups manipulation

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/jupytergis#40]
Quoting [these comments](https://github.com/QuantStack/jupytergis/issues/24#issuecomment-2202219458)

> I guess the kind of UI we'd want is being able to select multiple layers then `right-click` -> `group selection`, we'll need a context menu in your tree widget.
> 
> This context menu will be useful later for other commands.

@brichet :

> Yes, the context menu is a good option to create groups from layers.
> We probably also want drag and drop to move the layers individually.

**Comment by gjmooney** [comment]
Context menu: #48
Drag and Drop: #90
