### ISSUE TITLE
Closing file does not empty the left panel properly

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/jupytergis#66]
This test is failing since the changes in https://github.com/QuantStack/jupytergis/pull/48, we should look into fixing it

```javascript
test('should restore empty layer panel', async ({ page }) => {
   const layerTree = await openLayerTree(page);
   await page.activity.closeAll();
   await expect(layerTree).toBeEmpty();
});
```

[video.webm](https://github.com/user-attachments/assets/1d2a782c-d2c6-45f0-8134-526da0a84289)

**Comment by brichet** [comment]
I can't reproduce it anymore, and I see the test has been restored in https://github.com/QuantStack/jupytergis/pull/73.

Is it fixed now ?

**Comment by martinRenou** [comment]
Sounds like it! Thanks
