### ISSUE TITLE
[ENH] Add Scale to the Map

### ISSUE THREAD

**Issue by arjxn-py** [QuantStack/jupytergis#94]
This feature request proposes adding a scale to the map in JupyterGIS to enhance the user's ability to measure distances and understand the scale of the map. 

The scale can be easily added to the map using the `MapLibre.ScaleControl` class. Which would look like this: 

![ScreenRecording2024-08-18213013-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/1200decb-4e5e-41f6-9528-921b81e6e41a)

**Comment by arjxn-py** [comment]
I'd be happy to open a PR for the same if permitted.

**Comment by martinRenou** [comment]
> I'd be happy to open a PR for the same if permitted.

That would be very welcome :)
